[book]
authors = ["Monty Williams"]
language = "en"
multilingual = false
src = "src"
title = "The Mysterious Affair at Styles (in Open Sans font)"

[output.html]
curly-quotes = true
no-section-label = true
