[book]
authors = ["Monty Williams"]
language = "en"
multilingual = false
src = "src"
title = "The Mysterious Affair at Styles (in GentiumBookBasic font)"

[output.html]
theme = "src/ipython-theme"
additional-css = ["src/Gutenberg.css"]
git-repository-url = "https://github.com/Monty/mdbook-experiment"
curly-quotes = true
no-section-label = true
