[book]
authors = ["Monty Williams"]
language = "en"
multilingual = false
src = "src"
title = "The Mysterious Affair at Styles (in Arial font)"

[output.html]
additional-css = ["src/font-family.css", "src/Gutenberg.css"]
git-repository-url = "https://github.com/Monty/mdbook-experiment"
curly-quotes = true
no-section-label = true
